# Generated by Django 5.0.1 on 2024-01-24 10:29

import app_pereval.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default=None, max_length=30, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=8, verbose_name='Широта')),
                ('longitude', models.FloatField(max_length=8, verbose_name='Долгота')),
                ('height', models.IntegerField(max_length=4, verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], default='', max_length=2, verbose_name='Категория трудности: ЗИМА')),
                ('summer', models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], default='', max_length=2, verbose_name='Категория трудности: ЛЕТО')),
                ('autumn', models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], default='', max_length=2, verbose_name='Категория трудности: ОСЕНЬ')),
                ('spring', models.CharField(choices=[('', 'не указано'), ('1A', '1a'), ('1B', '1б'), ('2А', '2а'), ('2В', '2б'), ('3А', '3а'), ('3В', '3б')], default='', max_length=2, verbose_name='Категория трудности: ВЕСНА')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'на модерации'), ('accepted', 'принят'), ('rejected', 'не принят')], default='new', max_length=100, verbose_name='Статус модерации')),
                ('beauty_title', models.CharField(max_length=250, verbose_name='Тип локации')),
                ('title', models.CharField(max_length=250, verbose_name='Название локации')),
                ('other_titles', models.CharField(blank=True, default=None, max_length=250, verbose_name='Описание локации')),
                ('connect', models.CharField(max_length=250, verbose_name='Какие локации соединяет?')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('coord_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_pereval.coords', verbose_name='Координаты')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app_pereval.level', verbose_name='Категория трудности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pereval.appuser', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('images', models.ImageField(blank=True, default=None, null=True, upload_to=app_pereval.models.get_path_upload_images, verbose_name='Фото')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_pereval.pereval', verbose_name='Локация')),
            ],
        ),
    ]
