# Generated by Django 5.0.1 on 2024-02-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(verbose_name='Высота'),
        ),
    ]
